//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.BoardGameWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.tienda.proyecto.ws/", ConfigurationName="WSClient.BoardGameWS.IBoardGameWS")]
    public interface IBoardGameWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tienda.proyecto.ws/IBoardGameWS/updateRequest", ReplyAction="http://webservice.tienda.proyecto.ws/IBoardGameWS/updateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.BoardGameWS.updateResponse> updateAsync(WSClient.BoardGameWS.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tienda.proyecto.ws/IBoardGameWS/deleteRequest", ReplyAction="http://webservice.tienda.proyecto.ws/IBoardGameWS/deleteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.BoardGameWS.deleteResponse> deleteAsync(WSClient.BoardGameWS.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tienda.proyecto.ws/IBoardGameWS/readRequest", ReplyAction="http://webservice.tienda.proyecto.ws/IBoardGameWS/readResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.BoardGameWS.readResponse> readAsync(WSClient.BoardGameWS.readRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tienda.proyecto.ws/IBoardGameWS/createRequest", ReplyAction="http://webservice.tienda.proyecto.ws/IBoardGameWS/createResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.BoardGameWS.createResponse> createAsync(WSClient.BoardGameWS.createRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.tienda.proyecto.ws/IBoardGameWS/readAllRequest", ReplyAction="http://webservice.tienda.proyecto.ws/IBoardGameWS/readAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSClient.BoardGameWS.readAllResponse> readAllAsync(WSClient.BoardGameWS.readAllRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.tienda.proyecto.ws/")]
    public partial class boardGame
    {
        
        private string descriptionField;
        
        private int idField;
        
        private string imageURLField;
        
        private string nameField;
        
        private string officialURLField;
        
        private string rulesURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string imageURL
        {
            get
            {
                return this.imageURLField;
            }
            set
            {
                this.imageURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string officialURL
        {
            get
            {
                return this.officialURLField;
            }
            set
            {
                this.officialURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string rulesURL
        {
            get
            {
                return this.rulesURLField;
            }
            set
            {
                this.rulesURLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://webservice.tienda.proyecto.ws/", IsWrapped=true)]
    public partial class updateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.tienda.proyecto.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.BoardGameWS.boardGame arg0;
        
        public updateRequest()
        {
        }
        
        public updateRequest(WSClient.BoardGameWS.boardGame arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://webservice.tienda.proyecto.ws/", IsWrapped=true)]
    public partial class updateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.tienda.proyecto.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateResponse()
        {
        }
        
        public updateResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://webservice.tienda.proyecto.ws/", IsWrapped=true)]
    public partial class deleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.tienda.proyecto.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public deleteRequest()
        {
        }
        
        public deleteRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://webservice.tienda.proyecto.ws/", IsWrapped=true)]
    public partial class deleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.tienda.proyecto.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteResponse()
        {
        }
        
        public deleteResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="read", WrapperNamespace="http://webservice.tienda.proyecto.ws/", IsWrapped=true)]
    public partial class readRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.tienda.proyecto.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public readRequest()
        {
        }
        
        public readRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readResponse", WrapperNamespace="http://webservice.tienda.proyecto.ws/", IsWrapped=true)]
    public partial class readResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.tienda.proyecto.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.BoardGameWS.boardGame @return;
        
        public readResponse()
        {
        }
        
        public readResponse(WSClient.BoardGameWS.boardGame @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://webservice.tienda.proyecto.ws/", IsWrapped=true)]
    public partial class createRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.tienda.proyecto.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.BoardGameWS.boardGame arg0;
        
        public createRequest()
        {
        }
        
        public createRequest(WSClient.BoardGameWS.boardGame arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://webservice.tienda.proyecto.ws/", IsWrapped=true)]
    public partial class createResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.tienda.proyecto.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createResponse()
        {
        }
        
        public createResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAll", WrapperNamespace="http://webservice.tienda.proyecto.ws/", IsWrapped=true)]
    public partial class readAllRequest
    {
        
        public readAllRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAllResponse", WrapperNamespace="http://webservice.tienda.proyecto.ws/", IsWrapped=true)]
    public partial class readAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.tienda.proyecto.ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSClient.BoardGameWS.boardGame[] @return;
        
        public readAllResponse()
        {
        }
        
        public readAllResponse(WSClient.BoardGameWS.boardGame[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IBoardGameWSChannel : WSClient.BoardGameWS.IBoardGameWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class BoardGameWSClient : System.ServiceModel.ClientBase<WSClient.BoardGameWS.IBoardGameWS>, WSClient.BoardGameWS.IBoardGameWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BoardGameWSClient() : 
                base(BoardGameWSClient.GetDefaultBinding(), BoardGameWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BoardGameWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoardGameWSClient(EndpointConfiguration endpointConfiguration) : 
                base(BoardGameWSClient.GetBindingForEndpoint(endpointConfiguration), BoardGameWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoardGameWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BoardGameWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoardGameWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BoardGameWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BoardGameWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.BoardGameWS.updateResponse> WSClient.BoardGameWS.IBoardGameWS.updateAsync(WSClient.BoardGameWS.updateRequest request)
        {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.BoardGameWS.updateResponse> updateAsync(WSClient.BoardGameWS.boardGame arg0)
        {
            WSClient.BoardGameWS.updateRequest inValue = new WSClient.BoardGameWS.updateRequest();
            inValue.arg0 = arg0;
            return ((WSClient.BoardGameWS.IBoardGameWS)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.BoardGameWS.deleteResponse> WSClient.BoardGameWS.IBoardGameWS.deleteAsync(WSClient.BoardGameWS.deleteRequest request)
        {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.BoardGameWS.deleteResponse> deleteAsync(string arg0)
        {
            WSClient.BoardGameWS.deleteRequest inValue = new WSClient.BoardGameWS.deleteRequest();
            inValue.arg0 = arg0;
            return ((WSClient.BoardGameWS.IBoardGameWS)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.BoardGameWS.readResponse> WSClient.BoardGameWS.IBoardGameWS.readAsync(WSClient.BoardGameWS.readRequest request)
        {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.BoardGameWS.readResponse> readAsync(string arg0)
        {
            WSClient.BoardGameWS.readRequest inValue = new WSClient.BoardGameWS.readRequest();
            inValue.arg0 = arg0;
            return ((WSClient.BoardGameWS.IBoardGameWS)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.BoardGameWS.createResponse> WSClient.BoardGameWS.IBoardGameWS.createAsync(WSClient.BoardGameWS.createRequest request)
        {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.BoardGameWS.createResponse> createAsync(WSClient.BoardGameWS.boardGame arg0)
        {
            WSClient.BoardGameWS.createRequest inValue = new WSClient.BoardGameWS.createRequest();
            inValue.arg0 = arg0;
            return ((WSClient.BoardGameWS.IBoardGameWS)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.BoardGameWS.readAllResponse> WSClient.BoardGameWS.IBoardGameWS.readAllAsync(WSClient.BoardGameWS.readAllRequest request)
        {
            return base.Channel.readAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.BoardGameWS.readAllResponse> readAllAsync()
        {
            WSClient.BoardGameWS.readAllRequest inValue = new WSClient.BoardGameWS.readAllRequest();
            return ((WSClient.BoardGameWS.IBoardGameWS)(this)).readAllAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BoardGameWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BoardGameWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/WS.Proyecto.Tienda/soapws/boardgame");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BoardGameWSClient.GetBindingForEndpoint(EndpointConfiguration.BoardGameWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BoardGameWSClient.GetEndpointAddress(EndpointConfiguration.BoardGameWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            BoardGameWSPort,
        }
    }
}
