// <auto-generated />
using WS.Proyecto.Mapa.WebAPI.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace WS.Proyecto.Mapa.WebAPI.Migrations
{
    [DbContext(typeof(PetitionsDbContext))]
    partial class PetitionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("WS.Proyecto.Mapa.WebAPI.Entities.Petitions", b => {
                
                b.Property<int>("Id").ValueGeneratedOnAdd();
                b.Property<double>("Latitude");
                b.Property<double>("Longitude");
                b.Property<string>("Username");
                b.Property<string>("BoardGame");
                
                b.HasKey("Id");
                b.ToTable("Petitions");
                b.HasData(
                    new
                    {
                        Id = 0,
                        Latitude = 40.495341,
                        Longitude = -4.551394,
                        Username = "damian",
                        BoardGame = "usmFRWCFjI"
                    },
                    new
                    {
                        Id = 1,
                        Latitude = 43.495341,
                        Longitude = -5.271394,
                        Username = "david",
                        BoardGame = "usmFRWCFjI"
                    },
                    new
                    {
                        Id = 2,
                        Latitude = 43.425341,
                        Longitude = -5.571394,
                        Username = "pablo",
                        BoardGame = "ZdHlXy4uxe"
                    },
                    new
                    {
                        Id = 3,
                        Latitude = 43.395341,
                        Longitude = -5.550094,
                        Username = "damian",
                        BoardGame = "KpKepc41At"
                    },
                    new
                    {
                        Id = 4,
                        Latitude = 43.540349,
                        Longitude = -5.67555,
                        Username = "pablo",
                        BoardGame = "usmFRWCFjI"
                    },
                    new
                    {
                        Id = 5,
                        Latitude = 43.268881,
                        Longitude = -6.711394,
                        Username = "pablo",
                        BoardGame = "KpKepc41At"
                    });
            });
        }
    }
}
